import type { Level } from '../game/types';

export const level3: Level = {
  id: 3,
  name: 'Escape Room',
  gridSize: 10,
  hintQuota: 3,
  arrows: [
    { id: 'c1', x: 5, y: 4, direction: 'down', length: 2 },
    { id: 'c2', x: 4, y: 9, direction: 'left', length: 2 },
    { id: 'c3', x: 9, y: 3, direction: 'left', length: 4 },
    { id: 'c4', x: 2, y: 2, direction: 'left', length: 2 },
    { id: 'c5', x: 4, y: 3, direction: 'up', length: 3 },
    { id: 'c6', x: 7, y: 4, direction: 'down', length: 2 },
    { id: 'c7', x: 7, y: 6, direction: 'down', length: 4 },
    { id: 'c8', x: 8, y: 4, direction: 'right', length: 2 },
    { id: 'c9', x: 2, y: 4, direction: 'down', length: 4 },
    { id: 'c10', x: 1, y: 3, direction: 'left', length: 2 },
    { id: 'c11', x: 2, y: 9, direction: 'left', length: 3 },
    { id: 'c12', x: 9, y: 6, direction: 'down', length: 2 },
    { id: 'c13', x: 5, y: 0, direction: 'right', length: 3 },
    { id: 'c14', x: 3, y: 8, direction: 'up', length: 2 },
    { id: 'c15', x: 3, y: 0, direction: 'left', length: 4 },
    { id: 'c16', x: 9, y: 8, direction: 'down', length: 2 },
    { id: 'c17', x: 1, y: 1, direction: 'left', length: 2 },
    { id: 'c18', x: 6, y: 4, direction: 'down', length: 2 },
    { id: 'c19', x: 5, y: 2, direction: 'right', length: 4 },
    { id: 'c20', x: 1, y: 8, direction: 'left', length: 2 },
    { id: 'c21', x: 5, y: 6, direction: 'down', length: 2 },
    { id: 'c22', x: 5, y: 8, direction: 'down', length: 2 },
    { id: 'c23', x: 8, y: 1, direction: 'right', length: 2 },
    { id: 'c24', x: 6, y: 7, direction: 'down', length: 3 },
    { id: 'c25', x: 8, y: 8, direction: 'down', length: 2 },
  ],
};
