/* Auto-generated by scripts/generate-levels.ts — do not edit. */
import type { LevelFile } from '../game/types';
import level01 from './json/level-01.json';
import level02 from './json/level-02.json';
import level03 from './json/level-03.json';
import level04 from './json/level-04.json';
import level05 from './json/level-05.json';
import level06 from './json/level-06.json';
import level07 from './json/level-07.json';
import level08 from './json/level-08.json';
import level09 from './json/level-09.json';
import level10 from './json/level-10.json';
import level11 from './json/level-11.json';
import level12 from './json/level-12.json';
import level13 from './json/level-13.json';
import level14 from './json/level-14.json';
import level15 from './json/level-15.json';
import level16 from './json/level-16.json';
import level17 from './json/level-17.json';
import level18 from './json/level-18.json';
import level19 from './json/level-19.json';
import level20 from './json/level-20.json';
import level21 from './json/level-21.json';
import level22 from './json/level-22.json';
import level23 from './json/level-23.json';
import level24 from './json/level-24.json';
import level25 from './json/level-25.json';
import level26 from './json/level-26.json';
import level27 from './json/level-27.json';
import level28 from './json/level-28.json';
import level29 from './json/level-29.json';
import level30 from './json/level-30.json';
import level31 from './json/level-31.json';
import level32 from './json/level-32.json';
import level33 from './json/level-33.json';
import level34 from './json/level-34.json';
import level35 from './json/level-35.json';
import level36 from './json/level-36.json';
import level37 from './json/level-37.json';
import level38 from './json/level-38.json';
import level39 from './json/level-39.json';
import level40 from './json/level-40.json';
import level41 from './json/level-41.json';
import level42 from './json/level-42.json';
import level43 from './json/level-43.json';
import level44 from './json/level-44.json';
import level45 from './json/level-45.json';
import level46 from './json/level-46.json';
import level47 from './json/level-47.json';
import level48 from './json/level-48.json';
import level49 from './json/level-49.json';
import level50 from './json/level-50.json';

export const LEVEL_FILES: LevelFile[] = [
  level01,
  level02,
  level03,
  level04,
  level05,
  level06,
  level07,
  level08,
  level09,
  level10,
  level11,
  level12,
  level13,
  level14,
  level15,
  level16,
  level17,
  level18,
  level19,
  level20,
  level21,
  level22,
  level23,
  level24,
  level25,
  level26,
  level27,
  level28,
  level29,
  level30,
  level31,
  level32,
  level33,
  level34,
  level35,
  level36,
  level37,
  level38,
  level39,
  level40,
  level41,
  level42,
  level43,
  level44,
  level45,
  level46,
  level47,
  level48,
  level49,
  level50,
] as LevelFile[];
