/**
 * Offline generator: writes src/levels/json/level-XX.json and a registry.
 *
 *   npm run generate-levels
 */
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { generateLevel } from '../src/generator/levelGenerator';
import { validateLevel } from '../src/game/solver';

const OUT_DIR = join(process.cwd(), 'src', 'levels', 'json');
const REGISTRY_PATH = join(process.cwd(), 'src', 'levels', 'registry.ts');

const from = Number(process.env.LEVEL_FROM ?? 1);
const to = Number(process.env.LEVEL_TO ?? 50);

mkdirSync(OUT_DIR, { recursive: true });

const imports: string[] = [];
const entries: string[] = [];
let failures = 0;

for (let n = from; n <= to; n++) {
  const started = Date.now();
  process.stdout.write(`Generating level ${n}... `);

  const result = generateLevel(n);
  if (!result) {
    console.log('FAILED');
    failures++;
    continue;
  }

  const check = validateLevel(result.level);
  if (!check.valid || !check.solvable) {
    console.log('INVALID', check.errors);
    failures++;
    continue;
  }

  const fileName = `level-${String(n).padStart(2, '0')}.json`;
  const filePath = join(OUT_DIR, fileName);
  writeFileSync(filePath, `${JSON.stringify(result.file, null, 2)}\n`, 'utf8');

  const importName = `level${String(n).padStart(2, '0')}`;
  imports.push(`import ${importName} from './json/${fileName}';`);
  entries.push(`  ${importName},`);

  const s = result.file.stats;
  console.log(
    `OK (${Date.now() - started}ms) arrows=${s.arrowCount} score=${s.difficultyScore} ` +
      `avail=${s.initialAvailable} bends=${s.bendCount} sols=${s.solutionCount}`,
  );
}

const registry = `/* Auto-generated by scripts/generate-levels.ts — do not edit. */
import type { LevelFile } from '../game/types';
${imports.join('\n')}

export const LEVEL_FILES: LevelFile[] = [
${entries.join('\n')}
] as LevelFile[];
`;

writeFileSync(REGISTRY_PATH, registry, 'utf8');

if (failures > 0) {
  console.error(`\nFailed to generate ${failures} level(s).`);
  process.exit(1);
}

console.log(`\nWrote levels ${from}–${to} to ${OUT_DIR}`);
console.log(`Wrote registry ${REGISTRY_PATH}`);
